"""app launch tokens and sessions

Revision ID: 1abd42741864
Revises: 7d3122820cf2
Create Date: 2026-05-26 09:13:10.589689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString references


# revision identifiers, used by Alembic.
revision: str = '1abd42741864'
down_revision: Union[str, Sequence[str], None] = '7d3122820cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applaunchtoken',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('applaunchtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applaunchtoken_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_applaunchtoken_user_id'), ['user_id'], unique=False)

    op.create_table('appsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appsession_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_appsession_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appsession_user_id'))
        batch_op.drop_index(batch_op.f('ix_appsession_slug'))

    op.drop_table('appsession')
    with op.batch_alter_table('applaunchtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applaunchtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_applaunchtoken_slug'))

    op.drop_table('applaunchtoken')
    # ### end Alembic commands ###
