"""oauth: clients/codes/tokens for MCP OAuth (Claude.ai)

Revision ID: 2154c41b0659
Revises: 1ee4231bf6f8
Create Date: 2026-06-05 14:32:59.565065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString references


# revision identifiers, used by Alembic.
revision: str = '2154c41b0659'
down_revision: Union[str, Sequence[str], None] = '1ee4231bf6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthclient',
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('oauthpendingauthorization',
    sa.Column('txn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('txn')
    )
    with op.batch_alter_table('oauthpendingauthorization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauthpendingauthorization_client_id'), ['client_id'], unique=False)

    op.create_table('oauthcode',
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('code_hash')
    )
    with op.batch_alter_table('oauthcode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauthcode_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauthcode_user_id'), ['user_id'], unique=False)

    op.create_table('oauthtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauthtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauthtoken_access_token_hash'), ['access_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauthtoken_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauthtoken_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauthtoken_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauthtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauthtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauthtoken_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_oauthtoken_client_id'))
        batch_op.drop_index(batch_op.f('ix_oauthtoken_access_token_hash'))

    op.drop_table('oauthtoken')
    with op.batch_alter_table('oauthcode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauthcode_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauthcode_client_id'))

    op.drop_table('oauthcode')
    with op.batch_alter_table('oauthpendingauthorization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauthpendingauthorization_client_id'))

    op.drop_table('oauthpendingauthorization')
    op.drop_table('oauthclient')
    # ### end Alembic commands ###
