"""add app.allowed_services for per-app service scopes

Revision ID: 2a8feb74e75c
Revises: c26489e780bd
Create Date: 2026-05-26 19:25:22.473009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString references


# revision identifiers, used by Alembic.
revision: str = '2a8feb74e75c'
down_revision: Union[str, Sequence[str], None] = 'c26489e780bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_services', sa.JSON(), nullable=True))

    # Backfill: copy each existing app's declared ``services`` into
    # ``allowed_services`` so installed apps continue working without admin
    # action. Matches the fresh-install behavior in install_bundle (admin
    # uploaded the bundle → everything it declared is auto-approved). Apps
    # that declared nothing get an empty list, which the enforcement layer
    # treats as "no gating" for back-compat.
    bind = op.get_bind()
    bind.execute(sa.text(
        "UPDATE app SET allowed_services = COALESCE(services, '[]') "
        "WHERE allowed_services IS NULL"
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('allowed_services')

    # ### end Alembic commands ###
