"""add LoginAttempt + EmailSendLog tables for health dashboard

Revision ID: 4b2e4f669c6e
Revises: 74695b53b9bc
Create Date: 2026-05-26 19:36:34.371438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString references


# revision identifiers, used by Alembic.
revision: str = '4b2e4f669c6e'
down_revision: Union[str, Sequence[str], None] = '74695b53b9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loginattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loginattempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loginattempt_at'), ['at'], unique=False)

    op.create_table('emailsendlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emailsendlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emailsendlog_at'), ['at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailsendlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emailsendlog_at'))

    op.drop_table('emailsendlog')
    with op.batch_alter_table('loginattempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loginattempt_at'))

    op.drop_table('loginattempt')
    # ### end Alembic commands ###
