"""add app.csp_strict for opt-in strict CSP

Revision ID: 74695b53b9bc
Revises: 2a8feb74e75c
Create Date: 2026-05-26 19:32:43.488255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString references


# revision identifiers, used by Alembic.
revision: str = '74695b53b9bc'
down_revision: Union[str, Sequence[str], None] = '2a8feb74e75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOT NULL Boolean requires a server default for the backfill — SQLite
    # otherwise rejects ALTER ADD COLUMN on a populated table. Existing apps
    # default to False (legacy permissive CSP); new uploads override via the
    # manifest's permissions.csp_strict.
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'csp_strict',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
    # Drop the server default after backfill so the column behaves like the
    # rest of the boolean state in the table — values flow from the model.
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('csp_strict', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('csp_strict')

    # ### end Alembic commands ###
