"""add AuditEvent append-only audit log

Revision ID: b2f343b20d7e
Revises: ed5b4d944124
Create Date: 2026-05-27 10:25:11.570884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString references


# revision identifiers, used by Alembic.
revision: str = 'b2f343b20d7e'
down_revision: Union[str, Sequence[str], None] = 'ed5b4d944124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditevent_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_at'), ['at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditevent_at'))
        batch_op.drop_index(batch_op.f('ix_auditevent_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_auditevent_action'))

    op.drop_table('auditevent')
    # ### end Alembic commands ###
